### ISSUE TITLE
Add to PyPi?

### ISSUE THREAD

**Issue by justinclift** [mozilla/agithub#17]
Just went to install this, and discovered it's not on PyPi.

Any chance you can add it there, to keep things easy for potential users? :smile:

**Comment by kjkuan** [comment]
+1 at least add a setup.py so it can be installed via pip.

**Comment by marcoslhc** [comment]
I made a PR here https://github.com/jpaugh/agithub/pull/19 Hope it makes it...

**Comment by justinclift** [comment]
Good thinking. :smile:

**Comment by jpaugh** [comment]
Sorry guys! I'd like to say I've been off saving the world, but really I've just been busy with other things. I did merge in PR #19, though.

**Comment by marcoslhc** [comment]
Yep. I didn't package to PyPi because I'm not the owner. Meanwhile it needs to be installed from repo and build after that. I didn't have the time today to do a more elegant solution than this. I'll be working on that though.  Great job @jpaugh
Saludos…

Marcos Luis Hernández
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

1023 Pennsylvania Av. #11
Miami Beach, FL. 33139

[website]: http://xiryvella.com/ http://xiryvella.com/
[github]: https://github.com/marcoslhc https://github.com/marcoslhc
[twitter]: @marcoslhc http://twitter.com/marcoslhc
[public-key]: https://keybase.io/marcoslh https://keybase.io/marcoslh
[mobile]: +1 954 300 9924
[info]: https://www.google.com/profiles/marcoslhc https://www.google.com/profiles/marcoslhc

**Comment by jpaugh** [comment]
Awesome work @marcoslhc! You've given me the impetus to fix up the project some. I updated the `setup.py` (and project structure) quite a bit, and I hope it still works okay....

**Comment by blackwind** [comment]
Would you be so kind as to push v2.0 to PyPI, @jpaugh?

**Comment by jpaugh** [comment]
Hmm. The old version is on PyPI, but I've lost access to the account. I'll have to take it up with PyPI's admins... We shall see.

**Comment by jpaugh** [comment]
I've added a [support request](https://sourceforge.net/p/pypi/support-requests/606/) with the PyPi project.

**Comment by blackwind** [comment]
Looking through the SourceForge tracker, I'm not seeing any replies whatsoever. You might have better luck over at [Bitbucket](https://bitbucket.org/pypa/pypi/issues), which appears to be active.

**Comment by jpaugh** [comment]
Thanks, @blackwind! Done. https://bitbucket.org/pypa/pypi/issues/417/claim-package-agithub When did issue tracking become so fragmented? ;-)

**Comment by RSully** [comment]
Looks like that is at https://github.com/pypa/pypi-legacy/issues/417 now

**Comment by gene1wood** [comment]
The current status on this is that @jaredhobbs asked @jpaugh [back in August 2016](https://github.com/pypa/pypi-legacy/issues/417#issuecomment-239037620) what his pypi username was in order to transfer ownership of the pypi project from Jared to Jonathan. @jpaugh didn't reply in that ticket and the pypi project appears to still be owned by @jaredhobbs

@jpaugh also [implied he'd prefer if someone else would maintain the process of uploading to pypi](https://github.com/pypa/pypi-legacy/issues/417#issuecomment-239035278)

On the bright side, @jaredhobbs appears to have kept pypi up to date as it's version is the same as the one in the head of master.

**Comment by jaredhobbs** [comment]
@jpaugh I'd love to hand this over to you if you would confirm your pypi username for me!

**Comment by jpaugh** [comment]
@jaredhobbs Thank you, @jaredhobbs, for your efforts to maintain this in PyPi, and thank you all for your interest in the project. Unfortunately, I have lost interest in this project, and have been faking it (poorly) for some time now. I believe AGithub would be better off in someone else's hands. Please see #35 for details.

**Comment by jpaugh** [comment]
@jaredhobbs My pypi username is jpaugh. If you decide to transfer ownership to me, please let me know in a comment here. However, as per my announcement on issue #35, my only intention with Pypi is to transfer ownership of the project to a new maintainer, if one steps forward.

**Comment by jaredhobbs** [comment]
No problem! I'll just hang on to it until you've chosen a maintainer as per your post in #35.

**Comment by gene1wood** [comment]
@jaredhobbs Thanks for transferring the pypi ownership to me.

@jaredhobbs So in looking at the code [on pypi](https://pypi.python.org/pypi?:action=display&name=agithub&version=2.1) I see some discrepancies from the [2.1 release in GitHub](https://github.com/mozilla/agithub/tree/v2.1).

It looks like some automated cleanup was done by some piece of software between the source code and the pypi package release causing things like

* replacing `'` with `"`
* importing explicit classes from modules instead of `*`
* importing missing (e.g. `base64`) modules
* wrapping lines to be pep008 compatible
* removing duplicate methods (e.g. in the unit tests)

Any objections with whatever the next release is losing these automated changes that aren't reflected in the source code and working towards getting those types of changes (PEP008 conformance and other cleanup) into the source code so that what people are getting via pypi is the same as what's tagged in github?

**Comment by jaredhobbs** [comment]
I don't think that was automated clean up... I think that was my ocd cleanup in my own fork. Anyway, fine by me!

**Comment by gene1wood** [comment]
Sounds good. Do feel free to PR your fork with the cleanup.

I'll close this ticket out. At the moment I'm now also an owner of the [agithub pypi package](https://pypi.python.org/pypi/agithub), it's at v2.1 which maps to [Release v2.1](https://github.com/mozilla/agithub/releases/tag/v2.1)
