### ISSUE TITLE
Support Spotify API

### ISSUE THREAD

**Issue by ishanjoshi02** [mozilla/agithub#80]
Are there any plans to add Spotify API Client Support.

Another question that I have is, which APIs are being considered into adding to this Repository?

**Comment by gene1wood** [comment]
@ishanjoshi02 The intent of agithub is to be agnostic and extensible. If you'd like to use it with the spotify API that should be completely doable without adding anything (unless spotify has custom auth or something). If you find that spotify does require something agithub doesn't support, feel free to PR an addition of a spotify module.

> which APIs are being considered into adding to this Repository?

I'm not sure entirely what you mean by being considered. Any APIs that don't work natively with agithub because they have some custom aspects can be PRd to be added.
